#!/bin/bash

### BEGIN INIT INFO
# Provides: dropboxsync
# Required-Start: $local_fs $remote_fs $network $syslog
# Required-Stop: $local_fs $remote_fs $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Delay system logout while dropbox is running.
# Description: Enable service provided by firewall.sh.
### END INIT INFO

DBUSER=pedro

STATUS=$(sudo -u $DBUSER dropbox status)

if [ "$STATUS" == "Dropbox isn't running!" ]; then
    START=$(sudo -u $DBUSER dropbox start)
fi

COUNT_DONE=1
while true
do
    STATUS=$(sudo -u $DBUSER dropbox status)
    if [ "$STATUS" == "Up to date" ]; then
            COUNT_DONE=`expr $COUNT_DONE + 1`
            if [ $COUNT_DONE -gt 10 ]
            then
                    STOP=$(sudo -u $DBUSER dropbox stop)
                    break;
            fi
    fi
done
exit 0
