#!/bin/bash

MY_CONFIG_EXT=$(my config --ext-path)
PACKAGES_AVAILABLE=$(my config --all-pkg-path)
EXTENSION=$(my config --default-extension)
TARGET="$1"
source $MY_CONFIG_EXT/functions.sh

if empty "$TARGET"; then
  die "You need to pass a recipe name."
fi
if [[ -f $PACKAGES_AVAILABLE/$TARGET$EXTENSION ]]; then
  die "$TARGET recipe already exist."
fi
cp $MY_CONFIG_EXT/template $PACKAGES_AVAILABLE/$TARGET$EXTENSION
echo "$PACKAGES_AVAILABLE/$TARGET$EXTENSION"
