#!/bin/bash

source $(dirname $0)/../functions.sh

ACTION="$1"; shift;
MODE=${crypt_mode:="veracrypt"}

case "$ACTION" in
install )
  if [[ $(__exists $MODE) == "1" ]]; then
    __log "You already installed all packages for this plugin"
      exit
  fi

  case "$MODE" in
    veracrypt )
        if [[ $(__is_mac)=="1" ]]; then
          #it´s necessary to manually install OSXFuse with MacFuse support
          brew cask install veracrypt
          ln -s /Applications/VeraCrypt.app/Contents/MacOS/VeraCrypt /usr/local/bin/veracrypt
        else
          sudo add-apt-repository ppa:unit193/encryption
          sudo apt-get update
          sudo apt-get install exfat-fuse exfat-utils
          sudo apt-get install veracrypt
        fi
      ;;
    encfs )
        if [[ $(__is_mac)=="1" ]]; then
          __brew_install homebrew/fuse/encfs
        else
          sudo apt-get -y install encfs
        fi
      ;;
    * )
      __log "Mode $MODE not supported."
     ;;
  esac


;;
remove )
  case "$MODE" in
    veracrypt )
        if [[ $(__is_mac)=="1" ]]; then
          brew cask uninstall veracrypt
        else
          sudo apt-get remove veracrypt
        fi
      ;;
    encfs )
        if [[ $(__is_mac)=="1" ]]; then
          brew uninstall homebrew/fuse/encfs
        fi
      ;;
    * )
      __log "Mode $MODE not supported."
     ;;
  esac

;;
createVault )
  DEVICE="$1"
  DEVICE=${DEVICE:=$crypt_volume_folder/$crypt_volume_name$crypt_volume_extension}
  case "$MODE" in
    veracrypt )

        if [[ ! -d $(dirname $DEVICE) ]]; then
          sudo mkdir -p $(dirname $DEVICE)
        fi

        if [[ -e $DEVICE ]]; then
          __log "Block device $DEVICE already exist. Choose another volume name."
          exit 2
        fi

        veracrypt -t -c --encryption=AES-Twofish -k="" --filesystem=exFAT --hash=SHA512 --volume-type=normal --size=50M $DEVICE
      ;;
    encfs )
      __log "When using $MODE, you can execute 'openVault' directly"
      ;;
    * )
      __log "Mode $MODE not supported."
     ;;
  esac

;;
openVault )
  DEVICE="$1"
  MOUNTPOUNT="$2"
  DEVICE=${DEVICE:=$crypt_volume_folder/$crypt_volume_name$crypt_volume_extension}
  MOUNTPOINT=${MOUNTPOINT:=$crypt_mount_folder/$crypt_volume_name}
  case "$MODE" in
    veracrypt )

        if [[ ! $(__is_mac == "1") && ! -d $MOUNTPOINT ]]; then
          sudo mkdir -p $MOUNTPOINT
        fi

        if [ ! -e "$DEVICE" ]; then
          echo "Error: $DEVICE must be a block device."
          __log "Please, pass as argument or put in the configuration file."
          exit 2
        fi
        shift 2
        veracrypt -t --mount --protect-hidden=no -k "" $DEVICE $MOUNTPOINT
      ;;
    encfs )
        encfs $DEVICE $MOUNTPOINT -- -o volname="My Vault"
      ;;
    * )
      __log "Mode $MODE not supported."
     ;;
  esac

;;
closeVault )
  DEVICE="$1"
  case "$MODE" in
    veracrypt )
        DEVICE=${DEVICE:=$crypt_volume_folder/$crypt_volume_name$crypt_volume_extension}
        veracrypt -t -d $DEVICE
      ;;
    encfs )
        DEVICE=${DEVICE:=$crypt_mount_folder/$crypt_volume_name}
        umount $DEVICE
      ;;
    * )
      __log "Mode $MODE not supported."
     ;;
  esac

;;
*)

;;
esac
