#!/bin/bash

source $(dirname $0)/../functions.sh

ACTION="$1"; shift;

case "$ACTION" in
install )
  if [[ $(__exists veracrypt) == "1" ]]; then
    __log "You already installed all packages for this plugin"
      exit
  fi

  if [[ $(__is_mac)=="1" ]]; then
    #it´s necessary to manually install OSXFuse with MacFuse support
    brew cask install veracrypt
    ln -s /Applications/VeraCrypt.app/Contents/MacOS/VeraCrypt /usr/local/bin/veracrypt
  else
    sudo add-apt-repository ppa:unit193/encryption
    sudo apt-get update
    sudo apt-get install veracrypt
  fi

;;
remove )
  if [[ $(__is_mac)=="1" ]]; then
    brew cask uninstall veracrypt
  else
    sudo apt-get remove veracrypt
  fi
;;
createVault )
  DEVICE="$1"
  DEVICE=${DEVICE:=$crypt_volume_folder/$crypt_volume_name$crypt_volume_extension}

  if [[ ! -d $(dirname $DEVICE) ]]; then
    sudo mkdir -p $(dirname $DEVICE)
  fi

  if [[ -e $DEVICE ]]; then
    __log "Block device $DEVICE already exist. Choose another volume name."
    exit 2
  fi

  veracrypt -t -c --encryption=AES-Twofish -k="" --filesystem=exFAT --hash=SHA512 --volume-type=normal --size=50M $DEVICE
;;
openVault )
  DEVICE="$1"
  MOUNTPOUNT="$2"
  DEVICE=${DEVICE:=$crypt_volume_folder/$crypt_volume_name$crypt_volume_extension}
  MOUNTPOINT=${MOUNTPOINT:=$crypt_mount_folder/$crypt_volume_name}

  if [[ ! $(__is_mac == "1") && ! -d $MOUNTPOINT ]]; then
    sudo mkdir -p $MOUNTPOINT
  fi

  if [ ! -e "$DEVICE" ]; then
    echo "Error: $DEVICE must be a block device."
    __log "Please, pass as argument or put in the configuration file."
    exit 2
  fi
  shift 2
  #veracrypt -t --mount /Users/Pedro/Dropbox/Env/vault /Volumes/vault
  veracrypt -t --mount --protect-hidden=no -k "" $DEVICE $MOUNTPOINT
;;
closeVault )
  DEVICE="$1"
  DEVICE=${DEVICE:=$crypt_volume_folder/$crypt_volume_name$crypt_volume_extension}
  veracrypt -t -d $DEVICE
;;
*)

;;
esac
