#!/bin/bash

MY_CONFIG_EXT=$(myconf --ext-path)
source $MY_CONFIG_EXT/functions.sh
source $MY_CONFIG_EXT/ext_Setup.sh

TARGET="$1"
PACKAGES_AVAILABLE=$(myconf --all-pkg-path)
EXT=$(myconf --default-extension)
PACKAGE_LOCATION=$(myconf --pkg-path)

if [ -z "$TARGET" ]; then
    __warning "You need to pass the script target"
    exit 0
fi
if [ -z $(ls $PACKAGES_AVAILABLE/*$TARGET$EXT) ]; then
    __warning "Script doesn't exist."
    exit 0
fi
ln -sf $(ls $PACKAGES_AVAILABLE/*$TARGET$EXT) $PACKAGE_LOCATION/
if [[ -d $PACKAGES_AVAILABLE/rc/$TARGET ]]; then
  mkdir -p $PACKAGE_LOCATION/rc/$TARGET
  ln -sf $PACKAGES_AVAILABLE/rc/$TARGET/* $PACKAGE_LOCATION/rc/$TARGET
fi
