#!/bin/bash

MY_CONFIG_EXT=$(my config --ext-path)
source $MY_CONFIG_EXT/functions.sh

TARGET="$1"
EXTENSION=$(my config --default-extension)
PACKAGE_LOCATION=$(my config --pkg-path)

if empty "$TARGET"; then
   die "You need to pass a recipe name."
fi
rm $( ls $PACKAGE_LOCATION/$TARGET$EXTENSION )
rm -rf $PACKAGE_LOCATION/extra/$TARGET
