#!/bin/bash

MY_CONFIG_EXT=$(my config --ext-path)
source $MY_CONFIG_EXT/functions.sh

TARGET="$1"
EXT=$(my config --default-extension)
PACKAGE_LOCATION=$(my config --pkg-path)

if [ -z $TARGET ]; then
   warn "You need to pass the script target"
   exit 0
fi
rm $( ls $PACKAGE_LOCATION/$TARGET$EXT )
rm -rf $PACKAGE_LOCATION/rc/$TARGET
