#!/bin/bash

MY_CONFIG_EXT=$(myconf --ext-path)
PACKAGES_AVAILABLE=$(myconf --all-pkg-path)
EXT=$(myconf --default-extension)
TARGET="$1"
source $MY_CONFIG_EXT/functions.sh

if [ -z "$TARGET" ]; then
  warn "You need to pass the script name"
  exit 0
fi
if [[ -f $PACKAGES_AVAILABLE/$TARGET$EXT ]]; then
  warn "$TARGET script already exist."
  exit 0
fi
cp $MY_CONFIG_EXT/template $PACKAGES_AVAILABLE/$TARGET$EXT
