#!/bin/bash

MY_CONFIG_EXT=$(my config --ext-path)
source $MY_CONFIG_EXT/functions.sh

TARGET="$1"
PACKAGES_AVAILABLE=$(my config --all-pkg-path)
EXT=$(my config --default-extension)
PACKAGE_LOCATION=$(my config --pkg-path)

if [ -z "$TARGET" ]; then
    warn "You need to pass the script target"
    exit 0
fi
if [ -z $(ls $PACKAGES_AVAILABLE/*$TARGET$EXT) ]; then
    warn "Script doesn't exist."
    exit 0
fi
ln -sf $(ls $PACKAGES_AVAILABLE/*$TARGET$EXT) $PACKAGE_LOCATION/
if [[ -d $PACKAGES_AVAILABLE/rc/$TARGET ]]; then
  mkdir -p $PACKAGE_LOCATION/rc/$TARGET
  ln -sf $PACKAGES_AVAILABLE/rc/$TARGET/* $PACKAGE_LOCATION/rc/$TARGET
fi
