#!/bin/bash
source $MY_CONFIG_EXT/functions.sh

my_require apache
case "$1" in
install)
    sudo a2enmod ssl
    sudo service apache2 restart
    sudo mkdir /etc/apache2/ssl
    sudo openssl req -x509 -nodes -days 365 -newkey rsa:2040 -keyout
    /etc/apache2/ssl/apache.key -out /etc/apache2/ssl/apache.crt

    #TODO https://www.digitalocean.com/community/tutorials/how-to-create-a-ssl-certificate-on-apache-for-ubuntu-12-04
;;
remove)
;;
esac
