#!/bin/bash

NC="\033[0m"
BLACK="\033[0;30m"
RED="\033[0;31m"
GREEN="\033[0;32m"
ORANGE="\033[0;33m"
BLUE="\033[0;34m"
PURPLE="\033[0;35m"
CYAN="\033[0;36m"
LGRAY="\033[0;37m"
DGRAY="\033[1;30m"
LRED="\033[1;31m"
LGREEN="\033[1;32m"
YELLOW="\033[1;33m"
LBLUE="\033[1;34m"
LPURPLE="\033[1;35m"
LCYAN="\033[1;36m"
WHITE="\033[1;37m"

QUESTION_FLAG="${GREEN}?"
WARNING_FLAG="${YELLOW}!"
NOTICE_FLAG="${CYAN}❯"

__verbosity(){
   if [ "$1" == "on" ]; then
      export VERBOSE_MODE=1;
   fi
}

__log(){
  if [ ! -z "VERBOSE_MODE" ]; then
      echo -e "$1"
  fi
}

__notification(){
  __log "${NOTICE_FLAG}$1${NC}"
}

__question(){
  __log "${QUESTION_FLAG}$1${NC}"
}

__warning(){
  __log "${WARNING_FLAG}$1${NC}"
}
