#!/usr/bin/env bash
set -e
# shellcheck disable=SC2034
printf -v USAGE "%s" "[options] [<args>]"
# shellcheck disable=SC2034
LONG_USAGE=""
# shellcheck source=ext/plugins/my-config.helper
source $MY_CONFIG_EXT/plugins/config/my-config.helper

__config_backup(){
  local url
  if ask_boolean "This will overwrite remote hooks. Proceed?"; then
    __configure_gist_url
    url="$(__get_gist_url)"
    if ! empty $url; then
      gist -u $url $HOOK_FOLDER/* > /dev/null 2>&1
      note -f "Backup completed."
    fi
  fi
}
