#!/usr/bin/env bash

printf -v USAGE "%s" "[<recipe_name>]"
printf -v LONG_USAGE "%s" "Create a new (at first disabled) recipe.

     args
      [<recipe_name>] a recipe name."

__config_extra(){
  local target action
  target="$1"; shift;
  action="${1:-install}"; shift
  verbosity on
  ! empty "$target" || die "A target recipe must be informed."
  __open_hook_file "${target}.${action}"
  note "Hook to ${action} ${target} created."
}
