#!/bin/bash
source $MY_CONFIG_EXT/functions.sh

my_require apache git mysql
case "$1" in
install)
    sudo apt-get install graphviz aspell php5-pspell php5-curl php5-gd php5-intl php5-mysql php5-xmlrpc php5-ldap
    sudo service apache2 restart
    cd /opt
    sudo git clone git://git.moodle.org/moodle.git
    cd moodle
    sudo git branch -a
    sudo git branch --track MOODLE_28_STABLE origin/MOODLE_28_STABLE
    sudo git checkout MOODLE_28_STABLE

    sudo cp -R /opt/moodle /var/www/html
    sudo mkdir /var/moodledata
    sudo chown -R www-data /var/moodledata
    sudo chmod -R 777 /var/moodledata
    sudo chmod -R 0755 /var/www/html/moodle

    mysql -uroot -p -e "SET storage_engine=INNODB; CREATE DATABASE moodle DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;"
    echo "Enter your new moodle database user:"
    read -s mysqluser
    echo "Enter your new moodle database password:"
    read -s mysqlpass
    mysql -uroot -p -e "CREATE USER '$mysqluser'@'localhost' IDENTIFIED BY '$mysqlpass';"
    mysql -uroot -p -e "GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,CREATE TEMPORARY TABLES,DROP,INDEX,ALTER ON moodle.* TO '$mysqluser'@localhost IDENTIFIED BY '$mysqlpass';"

;;
remove)
;;
esac
